language: cpp

sudo: false

os:
  - linux
  - osx

compiler:
  - clang
  - gcc

before_install:
  - if [ $TRAVIS_OS_NAME = osx ]; then
      brew update;
    fi;

install:
  - if [ $TRAVIS_OS_NAME = linux ]; then
      if [ "$CXX" = "clang++" ]; then
        export CXX=clang++-3.7;
      elif [ "$CXX" = "g++" ]; then
        export CXX=g++-5;
      fi;
    elif [ $TRAVIS_OS_NAME = osx ]; then
      if [ "$CXX" = "clang++" ]; then
        brew install llvm36 && brew link --force llvm36;
        export CXX="clang++-3.6 -stdlib=libc++";
        export CXXFLAGS="$CXXFLAGS -nostdinc++ -I/usr/local/opt/llvm36/lib/llvm-3.6/include/c++/v1";
        export LDFLAGS="$LDFLAGS -L/usr/local/opt/llvm36/lib/llvm-3.6/lib";
      elif [ "$CXX" = "g++" ]; then
        brew outdated gcc || brew upgrade gcc;
        brew unlink boost; brew install boost --cc=gcc-5;
        export CXX=g++-5;
      fi;
    fi;
env:
  global:
   - secure: "R+NxqtytOslIcQ/eCbLoZhImsgYdJnljfjANdieFQGune9ACPPQL0YanXkF49c9SWGBSxrAcute0egQzv2CU2+ivSQIX/xnMebKHiOmSPYBoxX+VgxLT3U1itUYlpYwixo9rF8UnGdlgXid6oENSiCvfWtNKoM2qOL0Ttw31J9E="

addons:
  apt:
    sources:
      - boost-latest
      - ubuntu-toolchain-r-test
      - llvm-toolchain-precise-3.7
    packages:
      - clang-3.7
      - libstdc++-5-dev
      - g++-5
      - libncursesw5-dev
      - libboost-regex1.55-dev
  coverity_scan:
    project:
      name: "mawww/kakoune"
      description: "Build submitted via Travis CI"
    notification_email: frrrwww@gmail.com
    build_command_prepend: "cd src && make clean"
    build_command: "make -j4"
    branch_pattern: coverity-scan

matrix:
  exclude:
    - compiler: gcc
      os: osx

script: cd src && make && make test
